### ISSUE TITLE
Normalization parameters for feature extraction

### ISSUE THREAD

**Issue by zliubabalala** [HumamAlwassel/XDC#2]
Should I use the same mean and std parameters for normalization as r2plus1d in Pytorch, such as mean=[0.43216, 0.394666, 0.37645], std = [0.22803, 0.22145, 0.216989]?

**Comment by HumamAlwassel** [comment]
Thanks for your interest in XDC.

Yes, you should use these mean and std values.
```
mean = [0.43216, 0.394666, 0.37645]
std = [0.22803, 0.22145, 0.216989]
```

Cheers!
