### ISSUE TITLE
XDC pretrained on AudioSet

### ISSUE THREAD

**Issue by rogercmq** [HumamAlwassel/XDC#4]
I am wondering how to pretrain our r(2+1)d networks on AudioSet. Would scripts on preprocessing audio files be available?

**Comment by HumamAlwassel** [comment]
Hi @rogercmq,

For the audio encoder, we use a ResNet-18 with MelSpectoorgrams as the input. We do not plan on releasing any preprocessing scripts for the audio, but we recommend using the publicly available [`torchaudio`](https://pytorch.org/audio/stable/index.html) package. In particular, you can construct the MelSpectograms used by XDC following similar steps as in this `torchaudio` [tutorial](https://pytorch.org/tutorials/beginner/audio_preprocessing_tutorial.html#melspectrogram). We detail the audio preprocessing parameters (e.g. the number of Mel filters) in the XDC paper. 

Cheers,
Humam
