### ISSUE TITLE
Models for extracting audio features?

### ISSUE THREAD

**Issue by xjtupanda** [HumamAlwassel/XDC#9]
Thanks for sharing your pretrained models!
But if I did't get it wrong, the models are for extracting visual features. Could you please share the models for extracting corresponding audio features?

**Comment by HumamAlwassel** [comment]
Hello @xjtupanda,

Thanks for your interest in our work. 
Unfortunately, I no longer have access to these pretrained models after leaving FB. You might find this issue (https://github.com/HumamAlwassel/XDC/issues/4#issuecomment-847899813) helpful if you would like to pretrain your own audio encoder.

Cheers!
